website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for,jsonify
from .models import Book,User,Transaction
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user
views=Blueprint('views',__name__)

# @login_required
# def home():
#     return render_template("home.html")
@views.route('/')
@views.route('/search/',methods=['GET','POST'])
@login_required
def search():
    users = User.query
    book = request.args.get('bookname')
    if book:
        # get books like bookname that are not owned by current user
        books = Book.query.filter(Book.bookname.like(f'%{book}%'), Book.user_id != current_user.id)

        return render_template("search.html",books=books,users=users)
        
    return render_template("search.html")




@views.route('/add',methods=['GET','POST'])
@login_required
def add():
    if request.method=="POST":       
        bookname=request.form.get('bookname')
        authorname=request.form.get('authorname')
        genre=request.form.get('genre')
        review=request.form.get('review')
        new_book=Book(bookname=bookname,authorname=authorname,genre=genre,review=review,user_id=current_user.id)
        db.session.add(new_book)
        db.session.commit()

        return redirect(url_for('views.search'))
    return render_template("add.html", user=current_user)
@views.route('/profile',methods=['GET'])
@login_required
def profile():
    return render_template("profile.html",user=current_user)

    

@views.route('/about',methods=['GET'])
def about():
    return render_template("about.html")

@views.route('/changePassword',methods=['PUT'])
def getValue():
    data=request.get_json()
    old=data["oldpwd"]
    new=data["newpwd"]
    res={
        "message":"successfully changed the password",
    
    }
    return jsonify(res)

@views.route('/requestBook/<p1>/<p2>',methods=['GET','POST'])
@login_required
def requestBook(p1, p2):
    if request.method == 'POST':
        from_id = current_user.id
        book_id = p1
        to_id = p2
        message = request.form.get('request_message')
        new_transaction = Transaction(from_id=from_id, to_id=to_id, book_id=book_id, status='Pending', message=message)
        db.session.add(new_transaction)
        db.session.commit()
        print(message)

        return redirect(url_for('views.search'))
    return render_template("request.html")


@views.route('/requests',methods=['GET'])
@login_required
def requests():
    transactions = Transaction.query.filter_by(to_id=current_user.id)
    # return book info and requested person info via jinja
    book_names=[]
    user_names=[]
    messages=[]
    status=[]
    transaction_ids=[]
    emails=[]
    phonenumbers=[]
    for transaction in transactions:
        book_names.append(Book.query.filter_by(id=transaction.book_id).first().bookname)
        user_names.append(User.query.filter_by(id=transaction.from_id).first().username)
        messages.append(transaction.message)
        status.append(transaction.status)
        transaction_ids.append(transaction.id)
        if(transaction.status!="Approved"):
            emails.append("Hidden!!")
            phonenumbers.append("Hidden!!")
        else:
            emails.append(User.query.filter_by(id=transaction.from_id).first().email)
            phonenumbers.append(User.query.filter_by(id=transaction.from_id).first().phonenumber)

    return render_template("requests.html", transactions=transactions, book_names=book_names, user_names=user_names, messages=messages, status=status, transaction_ids=transaction_ids,emails=emails,phonenumbers=phonenumbers)

@views.route('/approve_request/<p1>',methods=['GET','POST'])
@login_required
def approve_request(p1):
    if request.method == 'POST':
        transaction = Transaction.query.filter_by(id=p1).first()
        transaction.status = 'Approved'
        db.session.commit()

        return redirect(url_for('views.requests'))
    return render_template("requests.html")

@views.route('/reject_request/<p1>',methods=['GET','POST'])
@login_required
def reject_request(p1):
    if request.method == 'POST':
        transaction = Transaction.query.filter_by(id=p1).first()
        transaction.status = 'Rejected'
        db.session.commit()

        return redirect(url_for('views.requests'))
    return render_template("requests.html")

@views.route('/myrequests',methods=['GET'])
@login_required
def myrequests():
    transactions = Transaction.query.filter_by(from_id=current_user.id)
    # return book info and requested person info via jinja
    book_names=[]
    user_names=[]
    messages=[]
    status=[]
    transaction_ids=[]
    emails = []
    phonenumbers =[]
    for transaction in transactions:
        book_names.append(Book.query.filter_by(id=transaction.book_id).first().bookname)
        user_names.append(User.query.filter_by(id=transaction.to_id).first().username)
        messages.append(transaction.message)
        status.append(transaction.status)
        transaction_ids.append(transaction.id)
        if(transaction.status!="Approved"):
            emails.append("Hidden!!")
            phonenumbers.append("Hidden!!")
        else:
            emails.append(User.query.filter_by(id=transaction.from_id).first().email)
            phonenumbers.append(User.query.filter_by(id=transaction.from_id).first().phonenumber)

    return render_template("myrequests.html", transactions=transactions, book_names=book_names, user_names=user_names, messages=messages, status=status, transaction_ids=transaction_ids,emails=emails,phonenumbers=phonenumbers)

website/templates/about.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <title>Book Swapper</title>
    <style>
        @import url('https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap');

        body {
            font-family: 'Poppins', sans-serif;
            background: linear-gradient(135deg, #86858d, #d8c3d0);
            color: #333;
            margin: 0;
            padding: 0;
        }

        .navbar {
            padding: 5px;
            position: sticky;
            top: 0;
            z-index: 100;
        }   
        .nav-item{
            padding: 2.5px;
        }

        .container {
            background: #fff;
            border-radius: 10px;
            box-shadow: 0 0 15px rgba(0, 0, 0, 0.2);
            padding: 20px;
            margin: 20px auto;
            max-width: 800px;
            min-width: 45%;
            transition: transform 0.2s, box-shadow 0.2s;
        }

        .container:hover {
            transform: scale(1.02);
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.3);
        }

        .container h1 {
            font-size: 30px;
            margin-bottom: 20px;
            color: #333;
        }

        .section {
            margin-bottom: 20px;
        }

        .section-title {
            font-size: 24px;
            font-weight: 600;
            margin-bottom: 10px;
        }

        .section p {
            font-size: 18px;
            line-height: 1.6;
        }

        img {
            width: 50px;
            height: 50px;
            display: block;
            margin: 20px auto;
        }
        .container-layout {
            padding: 10px;
        }

    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand">Book Swapper</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link active" href="/">Search Books</a>
                  </li>
          
                  <li class="nav-item">
                    <a class="nav-link" href="/add">Add Books</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/requests">Recieved</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/myrequests">Sent</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/profile">Profile</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/about">About</a>
                  </li>

            </ul>
            <a class="btn btn-outline-success my-2 my-sm-0" href="/logout">Logout</a>
        </div>
    </nav>

    <img src="https://freesvg.org/img/1488216538.png" alt="Logo">


    <div class="container-layout">
        <div class="container">
            <div class="section">
                <p>An initiative taken by a triad from IT department to increase the usage of books and to reduce the shortage in availability of books within the SSN community.</p>
            </div>
        </div>

        <div class="container">
            <div class="section">
                <p class="section-title">The Importance of Books</p>
                <p>Humans rely on books for information and knowledge. They have helped mankind evolve and have a deep impact on us and are responsible for uplifting our spirits. People say that books are their best friends. They are very useful for mankind and have enabled it to evolve. Books are a great source of information and knowledge. They give us a deep feeling of well-being.</p>
            </div>
        </div>

        <div class="container">
            <div class="section">
                <p class="section-title">The Challenge of Availability</p>
                <p>The benefits of books are well known. They have contributed to the evolution of mankind and have helped mankind to progress. Books have a profound impact on our lives and improve our moods. Currently, only 17–22 percent of books available in classroom collections are Nonfiction which gets declining every decade. A community consisting of a large member might have many utilized Fiction and Nonfiction books.</p>
            </div>
        </div>

        <div class="container">
            <div class="section">
                <p class="section-title">The Book Swapper Solution</p>
                <p>A member in a community might require a book where another member in the same community might have it and could be anonymous, and there could be a high possibility that the person could be an outsider. The idea is to develop a portal that can create interrelation between the community members and exchange information about the books they own. The community members should be able to list the books they are willing to exchange with others in the forum, and the database should store the information about the books listed by every user. Members should be able to search for the required book, and if it is available, the owner of the book can be contacted, private discussion can be done between them, and exchanges can be initiated.</p>
            </div>
        </div>
    </div>

</body>

</html>

website/templates/add.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
  <title>Book Swapper</title>
  <style>
    @import url('https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap');

    body {
      font-family: 'Poppins';
      background: linear-gradient(135deg, #86858d, #d8c3d0);
    }

    .navbar {
      padding: 5px;
      position: sticky;
      top: 0;
      z-index: 100;

    }

    .nav-item {
      padding: 2.5px;
    }

    .content-box {
      width: 60%;
      height: 55%;
      background: #ffffff;
      color: #020202;
      top: 50%;
      left: 50%;
      position: absolute;
      transform: translate(-50%, -50%);
      box-sizing: border-box;
      padding: 40px 30px;
      border: 3px solid black;
      border-radius: 15px;
    }

    h1 {
      margin: 0;
      padding: 0 0 20px;
      text-align: center;
      font-size: 22px;
    }

    .content-box input {
      width: inherit;
      margin-bottom: 20px;
    }

    .rows-1 {
      width: 100%;
      display: flex;
      justify-content: space-between;
    }

    .form-group {
      width: 100%;
      margin-left: 1%;
    }

    .rows-1 {
      width: 98%;
    }

    .rows-2 {
      width: 98%;
      display: flex;
    }

    .rows-3 {
      display: flex;
      margin-bottom: 2%;
    }

    .rows-4 {
      display: flex;
      justify-content: center;
    }
  </style>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand">Book Swapper</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link active" href="/">Search Books</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="/add">Add Books</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/requests">Recieved</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/myrequests">Sent</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/profile">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/about">About</a>
        </li>

      </ul>
      <a class="btn btn-outline-success my-2 my-sm-0" href="/logout">Logout</a>
    </div>
  </nav>


  <div class="content-box">
    <h1>Add Books 📚</h1>
    <form method="post">
      <div class="rows-1">
        <div class="form-group">
          <label for="bookname">Book Name</label>
          <input type="text" class="form-control" name="bookname" id="bookname" placeholder="Enter Bookname" required>
        </div>
      </div>

      <div class="rows-2">
        <div class="form-group">
          <label for="authorname">Author Name</label>
          <input type="text" class="form-control" name="authorname" id="authorname" placeholder="Enter Author Name"
            required>
        </div>
        <div class="form-group">
          <label for="genre">Genre</label>
          <input type="text" class="form-control" name="genre" id="genre" placeholder="Enter Genre" required>
        </div>
      </div>

      <div class="rows-3">
        <div class="form-group">
          <label for="review">Review</label>
          <textarea class="form-control" name="review" id="review" placeholder="Enter Review" required></textarea>
        </div>
      </div>

      <div class="rows-4">
        <button type="submit" class="btn btn-primary">Add ➕</button>
      </div>

    </form>
</body>

</html>

website/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <title>Book Swapper</title>
    <style>
        @import url('https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap');
      body {
        font-family: 'Poppins';
        background: linear-gradient(135deg, #86858d, #d8c3d0);
      }

      .loginbox {
        width: 380px;
        height: 420px;
        background: #ffffff;
        color: #020202;
        top: 50%;
        left: 50%;
        position: absolute;
        transform: translate(-50%, -50%);
        box-sizing: border-box;
        padding: 40px 30px;
        border: 3px solid black;
        border-radius: 15px;
      }

      h1 {
        margin: 0;
        padding: 0 0 20px;
        text-align: center;
        font-size: 22px;
      }

      .loginbox input {
        width: 100%;
        margin-bottom: 20px;
      }
      .loginbox a {
        text-decoration: none;
        font-size: 16px;
        line-height: 20px;
        color: darkgrey;
      }
      .loginbox a:hover {
        color: #564f5b;
      }
    </style>

  </head>
  <body>
    <div class="loginbox">
        <h1>Book Swapper</h1>
        <form method="post">
            <div class="form-group">
              <label for="Email">Email address</label>
              <input type="email" class="form-control" name="email" id="email" aria-describedby="emailHelp" placeholder="Enter email">
            </div>
            <div class="form-group">
              <label for="Password">Password</label>
              <input type="password" class="form-control" name="password" id="password" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
            <br>
            <a href="/register">Don't have an account?</a>
          </form>
          {% with messages = get_flashed_messages() %}  
          {% if messages %}  
                {% for message in messages %}  
                     <p style="color:rgb(247, 10, 10)">{{ message }}</p>                      
                {% endfor %}  
          {% endif %}  
       {% endwith %}  
    </div>
  </body>
</html>

website/templates/myRequests.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <title>Book Swapper - My Requests</title>
<style>
    @import url('https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap');

    body {
        width: 100%;
        height: 100%;
        font-family: 'Poppins';
        background: linear-gradient(135deg, #ffffff, #ffffff);
    }

    .navbar {
        padding: 5px;
        position: sticky;
        top: 0;
        z-index: 100;
    }

    .nav-item {
        padding: 2.5px;
    }

    .content-box {
        width: 60%;
        height: 20%;
        background: #ffffff;
        color: #020202;
        margin-top: 35%; /* Adjusted margin-top value */
        margin-left: 50%;
        transform: translate(-50%, -50%);
        box-sizing: border-box;
        padding: 40px 30px;
        border: 3px solid black;
        border-radius: 15px;
    }

    .content-box input,
    .content-box textarea {
        width: inherit;
        margin-bottom: 20px;
    }

    .request-box {
        display: flex;
        justify-content: space-between;
        margin-bottom: 20px;
        border: 1px solid #ccc;
        padding: 10px;
        border-radius: 5px;
    }

    .button-group {
        display: flex;
        gap: 10px;
    }
</style>

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand">Book Swapper</a>
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link active" href="/">Search Books</a>
                  </li>
          
                  <li class="nav-item">
                    <a class="nav-link" href="/add">Add Books</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/requests">Recieved</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/myrequests">Sent</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/profile">Profile</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/about">About</a>
                  </li>

            </ul>
            <a class="btn btn-outline-success my-2 my-sm-0" href="/logout">Logout</a>
        </div>
    </nav>
    <div class="content-box">
        {% if user_names %}
            {% for i in range(user_names|length - 1, -1, -1) %}
                <div class="request-box">
                    <div>
                        <p>User: {{ user_names[i] }}</p>
                        <p>Book: {{ book_names[i] }}</p>
                        <p>Message: {{ messages[i] }}</p>
                        <p>Email: {{ emails[i] }}</p>
                        <p>PhoneNumber: {{ phonenumbers[i] }}</p>
                    </div>
                    <div class="button-group">
                        <p>Status: {{ status[i] }}</p>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>No sent requests found.</p>
        {% endif %}
    </div>
</body>

</html>

website/templates/search.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
  <title>Book Swapper</title>
  <style>
    @import url('https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap');

    body {
      width: 100%;
      height: 100%;
      font-family: 'Poppins';
      background: linear-gradient(135deg, #ffffff, #ffffff);
    }

    .navbar {
      padding: 5px;
      position: sticky;
      top: 0;
      z-index: 100;

    }

    .nav-item {
      padding: 2.5px;
    }

    .content-box {
      width: 60%;
      height: 20%;
      background: #ffffff;
      color: #020202;
      margin-top: 10%;
      margin-left: 50%;
      transform: translate(-50%, -50%);
      box-sizing: border-box;
      padding: 40px 30px;
      border: 3px solid black;
      border-radius: 15px;
    }

    .content-box input {
      width: inherit;
      margin-bottom: 20px;
    }

    .rows-1 {
      width: 98%;
      display: flex;
      justify-content: space-between;
    }

    .form-group {
      width: 100%;
      margin-left: 1%;
    }

    .rows-4 {
      display: flex;
      justify-content: center;
    }

    .display {
      display: flex;
      flex-direction: column;
    }

    #requestBox {
      display: none;
    }

    .container {
      display: flex;
      width: 100%;
      justify-content: space-between;
      flex-wrap: wrap;


    }

    .border {
      width: 50%;
      padding: 1%;
    }
  </style>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand">Book Swapper</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <!-- <li class="nav-item">
              <a class="nav-link" href="/">Home</a>
            </li> -->
        <li class="nav-item active">
          <a class="nav-link active" href="/">Search Books</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="/add">Add Books</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/requests">Recieved</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/myrequests">Sent</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/profile">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/about">About</a>
        </li>

      </ul>
      <a class="btn btn-outline-success my-2 my-sm-0" href="/logout">Logout</a>
    </div>
  </nav>
  <div class="display">
    <div class="content-box">
      <form type="search">
        <div class="rows-1">
          <div class="form-group">
            <input type="text" class="form-control" name="bookname" id="bookname" placeholder="Search for a book . . ."
              required>
          </div>
        </div>
        <div class="rows-4">
          <button type="submit" class="btn btn-primary">Search 🔎</button>
        </div>
      </form>
    </div>
    <br>
    <div class="container">
      {% if books %}
      {% for book in books %}
      {% for user in users %}
      {% if book.user_id == user.id %}
      <div class="border border-dark rounded">
        <p>
          {{"Book Name : "}} {{book.bookname}} <br>
          {{"Book Author : "}} {{book.authorname}} <br>
          {{"Owner name : "}} {{user.username}} <br>
          {{"Owner email : "}} {{user.email}} <br>
          {{"Owner Phone : "}} {{user.phonenumber}} <br>
          
          <a href="{{url_for('views.requestBook',p1=book.id, p2 = book.user_id)}}">Request</a>
        </p>
      </div>
      {% endif %}
      {% endfor %}
      {% endfor %}
      {% endif %}
    </div>
    <script>
      var requestButtons = document.querySelectorAll('.request-button');
      requestButtons.forEach(function (button) {
        button.addEventListener('click', function () {
          var targetId = this.getAttribute('data-target');
          var requestBox = this.parentElement.querySelector('.' + targetId);
          if (requestBox.style.display === 'none' || requestBox.style.display === '') {
            requestBox.style.display = 'flex';
            this.style.display = 'none';
          }
        });
      });
    </script>
</body>

</html>